<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MyAccount</name>
   <tag></tag>
   <elementGuidId>aa789034-997d-44b8-b222-99a11df2a6d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.page-heading</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
