<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Authentication</name>
   <tag></tag>
   <elementGuidId>d7c312f4-0ddb-4832-b94d-bed951a3384e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.page-heading</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
